# pytorch_lightning==2.0.2
trainer:
  accelerator: gpu
  devices: 1
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: output/fsvi_fixaug/
      name: dsprites_ori-ver2-r8-wd1e-4-lr-0.2-rho-0.01-tmux-[14]-sigma-1.2
  max_epochs: 150
  # max_steps: 10000
  val_check_interval: 50
  num_sanity_val_steps: 0
model:
  sigma: 1.2
  model_name: vit-b16-224-dino
  training_mode: lora
  optimizer: svgd
  lr: 0.2
  momentum: 0.9
  weight_decay: 1e-4
  scheduler: cosine
  warmup_steps: 500
  rho: 0.01
  lora_r: 8
  lora_alpha: 8
  num_particles: 4
  cov_mat: False
  max_num_models: 20
  use_sam: True
  start_swa_step: 200
  swa_freq: 5
  use_swa_svgd: False 
  use_sym_kl: False
data:
  train_aug: False
  dataset: dsprites_ori
  root: ../Z.Data/vtab-1k/dsprites_ori
  size: 224
  batch_size: 32
  workers: 4
model_checkpoint:
  dirpath: saved_checkpoints
  filename: best-step-{step}-{val_acc:.4f}
  monitor: val_acc
  mode: max
  save_last: true
