# pytorch_lightning==2.0.2
trainer:
  accelerator: gpu
  devices: 1
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: output/fsvi/
      name: clevrcount-r16-lr-2-rho-0.05_fsvi_tmux-[8]_sigma_0.3  
  max_epochs: 150
  val_check_interval: 50
  num_sanity_val_steps: 0
model:
  model_name: vit-b16-224-dino
  training_mode: lora
  optimizer: svgd
  lr: 2
  momentum: 0.9
  weight_decay: 0.0
  scheduler: cosine
  warmup_steps: 500
  rho: 0.05
  lora_r: 16
  lora_alpha: 8
  num_particles: 4
  cov_mat: True
  max_num_models: 20
  use_sam: True
  start_swa_step: 200
  swa_freq: 1
  use_swa_svgd: False
  use_sym_kl: False
data:
  dataset: clevrcount
  root: ../Z.Data/vtab-1k/clevr_count
  size: 224
  batch_size: 64
  workers: 4
model_checkpoint:
  dirpath: saved_checkpoints
  filename: best-step-{step}-{val_acc:.4f}
  monitor: val_acc
  mode: max
  save_last: true
