# pytorch_lightning==2.0.2
trainer:
  accelerator: gpu
  devices: 1
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: output
      name: resisc45-r8
  max_epochs: 150
  val_check_interval: 50
  num_sanity_val_steps: 0
model:
  model_name: vit-b16-224-dino
  training_mode: lora
  optimizer: fhbi
  lr: 2
  momentum: 0.9
  weight_decay: 0.0
  scheduler: cosine
  warmup_steps: 500
  rho: 0.03
  lora_r: 8
  lora_alpha: 8
  num_particles: 4
  max_num_models: 20
  sigma: 1
data:
  transform_train_id: 1
  dataset: resisc45
  root: ../Z.Data/vtab-1k/resisc45
  size: 224
  batch_size: 12
  workers: 4
model_checkpoint:
  dirpath: saved_checkpoints
  filename: best-step-{step}-{val_acc:.4f}
  monitor: val_acc
  mode: max
  save_last: true
