# pytorch_lightning==2.0.2
trainer:
  accelerator: gpu
  devices: 1
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: output
      name: dsprloc-lora-r8-lr-0.15-rho0.03_SAM-[17]
  max_epochs: 150
  val_check_interval: 50
  num_sanity_val_steps: 0
model:
  model_name: vit-b16-224-dino
  training_mode: lora
  optimizer: svgd
  sigma: 1
  lr: 0.15
  momentum: 0.9
  weight_decay: 0.0
  scheduler: cosine
  warmup_steps: 500
  lora_r: 8
  rho: 0.03
  lora_alpha: 8
  num_particles: 1
  cov_mat: True
  max_num_models: 20
  use_sam: True
  start_swa_step: 65
  swa_freq: 5
  use_swa_svgd: False 
  use_sym_kl: False
data:
  dataset: dsprites_loc
  root: ../Z.Data/vtab-1k/dsprites_loc
  size: 224
  batch_size: 64
  workers: 4
  train_aug: False
model_checkpoint:
  dirpath: saved_checkpoints
  filename: best-step-{step}-{val_acc:.4f}
  monitor: val_acc
  mode: max
  save_last: true
