# pytorch_lightning==2.0.2
trainer:
  accelerator: gpu
  devices: 1
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: output
      name: cifar100-lora-r16-lr-0.008_svgd_1p_bs24_sam
  max_steps: 10000
  val_check_interval: 500
model:
  model_name: vit-b16-224-in21k
  training_mode: lora
  optimizer: svgd
  lr: 0.05
  momentum: 0.9
  weight_decay: 0.0
  scheduler: cosine
  warmup_steps: 500
  lora_r: 16
  lora_alpha: 16
  num_particles: 1
  use_sam: True
  weights_path: checkpoint/B_16.pth
data:
  dataset: cifar100
  root: ../Z.Data
  size: 224
  batch_size: 24
  workers: 4
model_checkpoint:
  filename: best-step-{step}-{val_acc:.4f}
  monitor: val_acc
  mode: max
  save_last: true
