# pytorch_lightning==2.0.2
trainer:
  accelerator: gpu
  devices: 1
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: output
      name: caltech-lora-r8-lr-0.15_svgd_4p_bs64_Sam_tmux[0]
  max_epochs: 200
  # max_steps: 10000
  val_check_interval: 30
model:
  model_name: vit-b16-224-dino
  training_mode: lora
  optimizer: svgd
  lr: 0.15
  rho: 0.05
  momentum: 0.9
  weight_decay: 1e-4
  scheduler: cosine
  warmup_steps: 500
  lora_r: 8
  lora_alpha: 8
  num_particles: 4
  use_sam: True
data:
  dataset: caltech101
  root: ../Z.Data/vtab-1k/caltech101/
  size: 224
  batch_size: 64
  workers: 4
model_checkpoint:
  dirpath: saved_checkpoints
  filename: best-step-{step}-{val_acc:.4f}
  monitor: val_acc
  mode: max
  save_last: true
