# pytorch_lightning==2.0.2
trainer:
  accelerator: gpu
  devices: 1
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: output
      name: dspritesori-size-64-lora-r8-lr-0.1_rho-0.05_1p_bs128_F_weightdecay_1e-4_Tuan_tune0
  max_epochs: 2000
  # max_steps: 10000
  val_check_interval: 30
model:
  model_name: vit-b16-224-in21k
  training_mode: lora
  optimizer: svgd
  rho: 0.05
  lr: 0.1
  momentum: 0.9
  weight_decay: 1e-4
  scheduler: cosine
  warmup_steps: 500
  lora_r: 8
  lora_alpha: 8
  num_particles: 1
  use_sam: True
  
data:
  dataset: dsprites_ori
  root: ../Z.Data/vtab-1k/dsprites_ori/
  size: 64
  batch_size: 128
  workers: 4
model_checkpoint:
  dirpath: saved_checkpoints
  filename: best-step-{step}-{val_acc:.4f}
  monitor: val_acc
  mode: max
  save_last: true
