# pytorch_lightning==2.0.2
trainer:
  accelerator: gpu
  devices: 1
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: output
      name: pets-lora-r8-lr-0.15_rho-0.03_1p_bs24_F
  max_epochs: 100
  # max_steps: 10000
  val_check_interval: 30
model:
  model_name: vit-b16-224-in21k
  training_mode: lora
  optimizer: svgd
  rho: 0.03
  lr: 0.15
  momentum: 0.9
  weight_decay: 0.0
  scheduler: cosine
  warmup_steps: 500
  lora_r: 8
  lora_alpha: 8
  num_particles: 1
  use_sam: True
  
data:
  dataset: pets37
  root: ../Z.Data/vtab-1k/oxford_iiit_pet/
  size: 224
  batch_size: 24
  workers: 4
model_checkpoint:
  dirpath: saved_checkpoints
  filename: best-step-{step}-{val_acc:.4f}
  monitor: val_acc
  mode: max
  save_last: true
